namespace HerPublicWebsite.BusinessLogic.Models;

public class LocalAuthorityData
{
    public enum Hug2Status
    {
        NotTakingPart,
        Pending,
        Live
    }
    
    public record LocalAuthorityDetails(string Name, Hug2Status Status, string WebsiteUrl);

    // The mapping from custodian code to name comes from the publicly available "Local custodian codes" download link
    // on https://www.ordnancesurvey.co.uk/business-government/tools-support/addressbase-support
    public static readonly Dictionary<string, LocalAuthorityDetails> LocalAuthorityDetailsByCustodianCode = new()
    {
        { "9052", new LocalAuthorityDetails("Aberdeenshire", Hug2Status.NotTakingPart, "") },
        { "3805", new LocalAuthorityDetails("Adur", Hug2Status.NotTakingPart, "") },
        { "905", new LocalAuthorityDetails("Allerdale", Hug2Status.NotTakingPart, "") },
        { "1005", new LocalAuthorityDetails("Amber Valley", Hug2Status.NotTakingPart, "") },
        { "9053", new LocalAuthorityDetails("Angus", Hug2Status.NotTakingPart, "") },
        { "9054", new LocalAuthorityDetails("Argyll and Bute", Hug2Status.NotTakingPart, "") },
        { "3810", new LocalAuthorityDetails("Arun", Hug2Status.NotTakingPart, "") },
        { "3005", new LocalAuthorityDetails("Ashfield", Hug2Status.NotTakingPart, "") },
        { "2205", new LocalAuthorityDetails("Ashford", Hug2Status.NotTakingPart, "") },
        { "3505", new LocalAuthorityDetails("Babergh", Hug2Status.NotTakingPart, "") },
        { "5060", new LocalAuthorityDetails("Barking and Dagenham", Hug2Status.NotTakingPart, "") },
        { "5090", new LocalAuthorityDetails("Barnet", Hug2Status.NotTakingPart, "") },
        { "4405", new LocalAuthorityDetails("Barnsley", Hug2Status.NotTakingPart, "") },
        { "910", new LocalAuthorityDetails("Barrow-In-Furness", Hug2Status.NotTakingPart, "") },
        { "1505", new LocalAuthorityDetails("Basildon", Hug2Status.NotTakingPart, "") },
        { "1705", new LocalAuthorityDetails("Basingstoke and Deane", Hug2Status.NotTakingPart, "") },
        { "3010", new LocalAuthorityDetails("Bassetlaw", Hug2Status.NotTakingPart, "") },
        { "114", new LocalAuthorityDetails("Bath and North East Somerset", Hug2Status.NotTakingPart, "") },
        { "235", new LocalAuthorityDetails("Bedford", Hug2Status.NotTakingPart, "") },
        { "5120", new LocalAuthorityDetails("Bexley", Hug2Status.NotTakingPart, "") },
        { "4605", new LocalAuthorityDetails("Birmingham", Hug2Status.NotTakingPart, "") },
        { "2405", new LocalAuthorityDetails("Blaby", Hug2Status.NotTakingPart, "") },
        { "2372", new LocalAuthorityDetails("Blackburn With Darwen", Hug2Status.NotTakingPart, "") },
        { "2373", new LocalAuthorityDetails("Blackpool", Hug2Status.NotTakingPart, "") },
        { "6910", new LocalAuthorityDetails("Blaenau Gwent", Hug2Status.NotTakingPart, "") },
        { "1010", new LocalAuthorityDetails("Bolsover", Hug2Status.NotTakingPart, "") },
        { "4205", new LocalAuthorityDetails("Bolton", Hug2Status.NotTakingPart, "") },
        { "2505", new LocalAuthorityDetails("Boston", Hug2Status.NotTakingPart, "") },
        { "1260", new LocalAuthorityDetails("Bournemouth Christchurch and Poole", Hug2Status.NotTakingPart, "") },
        { "335", new LocalAuthorityDetails("Bracknell Forest", Hug2Status.NotTakingPart, "") },
        { "4705", new LocalAuthorityDetails("Bradford Mdc", Hug2Status.NotTakingPart, "") },
        { "1510", new LocalAuthorityDetails("Braintree", Hug2Status.NotTakingPart, "") },
        { "2605", new LocalAuthorityDetails("Breckland", Hug2Status.NotTakingPart, "") },
        { "5150", new LocalAuthorityDetails("Brent", Hug2Status.NotTakingPart, "") },
        { "1515", new LocalAuthorityDetails("Brentwood", Hug2Status.NotTakingPart, "") },
        { "6915", new LocalAuthorityDetails("Bridgend County Borough", Hug2Status.NotTakingPart, "") },
        { "1445", new LocalAuthorityDetails("Brighton & Hove", Hug2Status.NotTakingPart, "") },
        { "116", new LocalAuthorityDetails("Bristol", Hug2Status.NotTakingPart, "") },
        { "2610", new LocalAuthorityDetails("Broadland", Hug2Status.NotTakingPart, "") },
        { "1805", new LocalAuthorityDetails("Bromsgrove", Hug2Status.NotTakingPart, "") },
        { "1905", new LocalAuthorityDetails("Broxbourne", Hug2Status.NotTakingPart, "") },
        { "3015", new LocalAuthorityDetails("Broxtowe", Hug2Status.NotTakingPart, "") },
        { "440", new LocalAuthorityDetails("Buckinghamshire", Hug2Status.NotTakingPart, "") },
        { "2315", new LocalAuthorityDetails("Burnley", Hug2Status.NotTakingPart, "") },
        { "4210", new LocalAuthorityDetails("Bury", Hug2Status.NotTakingPart, "") },
        { "6920", new LocalAuthorityDetails("Caerphilly County Borough", Hug2Status.NotTakingPart, "") },
        { "4710", new LocalAuthorityDetails("Calderdale", Hug2Status.NotTakingPart, "") },
        { "505", new LocalAuthorityDetails("Cambridge", Hug2Status.NotTakingPart, "") },
        { "5210", new LocalAuthorityDetails("Camden", Hug2Status.NotTakingPart, "") },
        { "3405", new LocalAuthorityDetails("Cannock Chase", Hug2Status.NotTakingPart, "") },
        { "2210", new LocalAuthorityDetails("Canterbury", Hug2Status.NotTakingPart, "") },
        { "6815", new LocalAuthorityDetails("Cardiff", Hug2Status.NotTakingPart, "") },
        { "915", new LocalAuthorityDetails("Carlisle", Hug2Status.NotTakingPart, "") },
        { "6825", new LocalAuthorityDetails("Carmarthenshire", Hug2Status.NotTakingPart, "") },
        { "1520", new LocalAuthorityDetails("Castle Point", Hug2Status.NotTakingPart, "") },
        { "240", new LocalAuthorityDetails("Central Bedfordshire", Hug2Status.NotTakingPart, "") },
        { "6820", new LocalAuthorityDetails("Ceredigion", Hug2Status.NotTakingPart, "") },
        { "2410", new LocalAuthorityDetails("Charnwood", Hug2Status.NotTakingPart, "") },
        { "1525", new LocalAuthorityDetails("Chelmsford", Hug2Status.NotTakingPart, "") },
        { "1605", new LocalAuthorityDetails("Cheltenham", Hug2Status.NotTakingPart, "") },
        { "3105", new LocalAuthorityDetails("Cherwell", Hug2Status.NotTakingPart, "") },
        { "660", new LocalAuthorityDetails("Cheshire East", Hug2Status.NotTakingPart, "") },
        { "665", new LocalAuthorityDetails("Cheshire West and Chester", Hug2Status.NotTakingPart, "") },
        { "1015", new LocalAuthorityDetails("Chesterfield", Hug2Status.NotTakingPart, "") },
        { "3815", new LocalAuthorityDetails("Chichester", Hug2Status.NotTakingPart, "") },
        { "2320", new LocalAuthorityDetails("Chorley", Hug2Status.NotTakingPart, "") },
        { "9051", new LocalAuthorityDetails("City of Aberdeen", Hug2Status.NotTakingPart, "") },
        { "9059", new LocalAuthorityDetails("City of Dundee", Hug2Status.NotTakingPart, "") },
        { "9064", new LocalAuthorityDetails("City of Edinburgh", Hug2Status.NotTakingPart, "") },
        { "9067", new LocalAuthorityDetails("City of Glasgow", Hug2Status.NotTakingPart, "") },
        { "5030", new LocalAuthorityDetails("City of London", Hug2Status.NotTakingPart, "") },
        { "3455", new LocalAuthorityDetails("City of Stoke-On-Trent", Hug2Status.NotTakingPart, "") },
        { "5990", new LocalAuthorityDetails("City of Westminster", Hug2Status.NotTakingPart, "") },
        { "9056", new LocalAuthorityDetails("Clackmannan", Hug2Status.NotTakingPart, "") },
        { "1530", new LocalAuthorityDetails("Colchester", Hug2Status.NotTakingPart, "") },
        { "6905", new LocalAuthorityDetails("Conwy", Hug2Status.NotTakingPart, "") },
        { "920", new LocalAuthorityDetails("Copeland", Hug2Status.NotTakingPart, "") },
        { "840", new LocalAuthorityDetails("Cornwall", Hug2Status.NotTakingPart, "") },
        { "1610", new LocalAuthorityDetails("Cotswold", Hug2Status.NotTakingPart, "") },
        { "4610", new LocalAuthorityDetails("Coventry", Hug2Status.NotTakingPart, "") },
        { "2705", new LocalAuthorityDetails("Craven", Hug2Status.NotTakingPart, "") },
        { "3820", new LocalAuthorityDetails("Crawley", Hug2Status.NotTakingPart, "") },
        { "5240", new LocalAuthorityDetails("Croydon", Hug2Status.NotTakingPart, "") },
        { "940", new LocalAuthorityDetails("Cumberland", Hug2Status.NotTakingPart, "") },
        { "1910", new LocalAuthorityDetails("Dacorum", Hug2Status.NotTakingPart, "") },
        { "1350", new LocalAuthorityDetails("Darlington", Hug2Status.NotTakingPart, "") },
        { "2215", new LocalAuthorityDetails("Dartford", Hug2Status.NotTakingPart, "") },
        { "6830", new LocalAuthorityDetails("Denbighshire", Hug2Status.NotTakingPart, "") },
        { "1055", new LocalAuthorityDetails("Derby", Hug2Status.NotTakingPart, "") },
        { "1045", new LocalAuthorityDetails("Derbyshire Dales", Hug2Status.NotTakingPart, "") },
        { "4410", new LocalAuthorityDetails("Doncaster", Hug2Status.NotTakingPart, "") },
        { "1265", new LocalAuthorityDetails("Dorset", Hug2Status.NotTakingPart, "") },
        { "2220", new LocalAuthorityDetails("Dover", Hug2Status.NotTakingPart, "") },
        { "4615", new LocalAuthorityDetails("Dudley", Hug2Status.NotTakingPart, "") },
        { "9058", new LocalAuthorityDetails("Dumfries and Galloway", Hug2Status.NotTakingPart, "") },
        { "1355", new LocalAuthorityDetails("Durham", Hug2Status.NotTakingPart, "") },
        { "5270", new LocalAuthorityDetails("Ealing", Hug2Status.NotTakingPart, "") },
        { "9060", new LocalAuthorityDetails("East Ayrshire", Hug2Status.NotTakingPart, "") },
        { "510", new LocalAuthorityDetails("East Cambridgeshire", Hug2Status.NotTakingPart, "") },
        { "1105", new LocalAuthorityDetails("East Devon", Hug2Status.NotTakingPart, "") },
        { "9061", new LocalAuthorityDetails("East Dunbartonshire", Hug2Status.NotTakingPart, "") },
        { "1710", new LocalAuthorityDetails("East Hampshire", Hug2Status.NotTakingPart, "") },
        { "1915", new LocalAuthorityDetails("East Hertfordshire", Hug2Status.NotTakingPart, "") },
        { "2510", new LocalAuthorityDetails("East Lindsey", Hug2Status.NotTakingPart, "") },
        { "9062", new LocalAuthorityDetails("East Lothian", Hug2Status.NotTakingPart, "") },
        { "9063", new LocalAuthorityDetails("East Renfrewshire", Hug2Status.NotTakingPart, "") },
        { "2001", new LocalAuthorityDetails("East Riding of Yorkshire", Hug2Status.NotTakingPart, "") },
        { "3410", new LocalAuthorityDetails("East Staffordshire", Hug2Status.NotTakingPart, "") },
        { "3540", new LocalAuthorityDetails("East Suffolk", Hug2Status.NotTakingPart, "") },
        { "1410", new LocalAuthorityDetails("Eastbourne", Hug2Status.NotTakingPart, "") },
        { "1715", new LocalAuthorityDetails("Eastleigh", Hug2Status.NotTakingPart, "") },
        { "925", new LocalAuthorityDetails("Eden", Hug2Status.NotTakingPart, "") },
        { "3605", new LocalAuthorityDetails("Elmbridge", Hug2Status.NotTakingPart, "") },
        { "5300", new LocalAuthorityDetails("Enfield", Hug2Status.NotTakingPart, "") },
        { "1535", new LocalAuthorityDetails("Epping Forest", Hug2Status.NotTakingPart, "") },
        { "3610", new LocalAuthorityDetails("Epsom and Ewell", Hug2Status.NotTakingPart, "") },
        { "1025", new LocalAuthorityDetails("Erewash", Hug2Status.NotTakingPart, "") },
        { "1110", new LocalAuthorityDetails("Exeter", Hug2Status.NotTakingPart, "") },
        { "9065", new LocalAuthorityDetails("Falkirk", Hug2Status.NotTakingPart, "") },
        { "1720", new LocalAuthorityDetails("Fareham", Hug2Status.NotTakingPart, "") },
        { "515", new LocalAuthorityDetails("Fenland", Hug2Status.NotTakingPart, "") },
        { "9066", new LocalAuthorityDetails("Fife", Hug2Status.NotTakingPart, "") },
        { "6835", new LocalAuthorityDetails("Flintshire", Hug2Status.NotTakingPart, "") },
        { "2250", new LocalAuthorityDetails("Folkestone and Hythe", Hug2Status.NotTakingPart, "") },
        { "1615", new LocalAuthorityDetails("Forest of Dean", Hug2Status.NotTakingPart, "") },
        { "2325", new LocalAuthorityDetails("Fylde", Hug2Status.NotTakingPart, "") },
        { "4505", new LocalAuthorityDetails("Gateshead", Hug2Status.NotTakingPart, "") },
        { "3020", new LocalAuthorityDetails("Gedling", Hug2Status.NotTakingPart, "") },
        { "1620", new LocalAuthorityDetails("Gloucester", Hug2Status.NotTakingPart, "") },
        { "1725", new LocalAuthorityDetails("Gosport", Hug2Status.NotTakingPart, "") },
        { "2230", new LocalAuthorityDetails("Gravesham", Hug2Status.NotTakingPart, "") },
        { "2615", new LocalAuthorityDetails("Great Yarmouth", Hug2Status.NotTakingPart, "") },
        { "5330", new LocalAuthorityDetails("Greenwich", Hug2Status.NotTakingPart, "") },
        { "3615", new LocalAuthorityDetails("Guildford", Hug2Status.NotTakingPart, "") },
        { "6810", new LocalAuthorityDetails("Gwynedd", Hug2Status.NotTakingPart, "") },
        { "5360", new LocalAuthorityDetails("Hackney", Hug2Status.NotTakingPart, "") },
        { "650", new LocalAuthorityDetails("Halton", Hug2Status.NotTakingPart, "") },
        { "2710", new LocalAuthorityDetails("Hambleton", Hug2Status.NotTakingPart, "") },
        { "5390", new LocalAuthorityDetails("Hammersmith and Fulham", Hug2Status.NotTakingPart, "") },
        { "2415", new LocalAuthorityDetails("Harborough", Hug2Status.NotTakingPart, "") },
        { "1540", new LocalAuthorityDetails("Harlow", Hug2Status.NotTakingPart, "") },
        { "2715", new LocalAuthorityDetails("Harrogate", Hug2Status.NotTakingPart, "") },
        { "5450", new LocalAuthorityDetails("Harrow", Hug2Status.NotTakingPart, "") },
        { "1730", new LocalAuthorityDetails("Hart", Hug2Status.NotTakingPart, "") },
        { "724", new LocalAuthorityDetails("Hartlepool", Hug2Status.NotTakingPart, "") },
        { "1415", new LocalAuthorityDetails("Hastings", Hug2Status.NotTakingPart, "") },
        { "1735", new LocalAuthorityDetails("Havant", Hug2Status.NotTakingPart, "") },
        { "5480", new LocalAuthorityDetails("Havering", Hug2Status.NotTakingPart, "") },
        { "1850", new LocalAuthorityDetails("Herefordshire", Hug2Status.NotTakingPart, "") },
        { "1920", new LocalAuthorityDetails("Hertsmere", Hug2Status.NotTakingPart, "") },
        { "1030", new LocalAuthorityDetails("High Peak", Hug2Status.NotTakingPart, "") },
        { "9068", new LocalAuthorityDetails("Highland", Hug2Status.NotTakingPart, "") },
        { "5510", new LocalAuthorityDetails("Hillingdon", Hug2Status.NotTakingPart, "") },
        { "2420", new LocalAuthorityDetails("Hinckley and Bosworth", Hug2Status.NotTakingPart, "") },
        { "3825", new LocalAuthorityDetails("Horsham", Hug2Status.NotTakingPart, "") },
        { "520", new LocalAuthorityDetails("Huntingdonshire", Hug2Status.NotTakingPart, "") },
        { "2330", new LocalAuthorityDetails("Hyndburn", Hug2Status.NotTakingPart, "") },
        { "9069", new LocalAuthorityDetails("Inverclyde", Hug2Status.NotTakingPart, "") },
        { "3515", new LocalAuthorityDetails("Ipswich", Hug2Status.NotTakingPart, "") },
        { "6805", new LocalAuthorityDetails("Isle of Anglesey", Hug2Status.NotTakingPart, "") },
        { "2114", new LocalAuthorityDetails("Isle of Wight", Hug2Status.NotTakingPart, "") },
        { "835", new LocalAuthorityDetails("Isles of Scilly", Hug2Status.NotTakingPart, "") },
        { "5570", new LocalAuthorityDetails("Islington", Hug2Status.NotTakingPart, "") },
        { "5600", new LocalAuthorityDetails("Kensington and Chelsea", Hug2Status.NotTakingPart, "") },
        { "2635", new LocalAuthorityDetails("Kings Lynn and West Norfolk", Hug2Status.NotTakingPart, "") },
        { "2004", new LocalAuthorityDetails("Kingston Upon Hull", Hug2Status.NotTakingPart, "") },
        { "5630", new LocalAuthorityDetails("Kingston Upon Thames", Hug2Status.NotTakingPart, "") },
        { "4715", new LocalAuthorityDetails("Kirklees", Hug2Status.NotTakingPart, "") },
        { "4305", new LocalAuthorityDetails("Knowsley", Hug2Status.NotTakingPart, "") },
        { "5660", new LocalAuthorityDetails("Lambeth", Hug2Status.NotTakingPart, "") },
        { "2335", new LocalAuthorityDetails("Lancaster City", Hug2Status.NotTakingPart, "") },
        { "4720", new LocalAuthorityDetails("Leeds", Hug2Status.NotTakingPart, "") },
        { "2465", new LocalAuthorityDetails("Leicester City", Hug2Status.NotTakingPart, "") },
        { "1425", new LocalAuthorityDetails("Lewes", Hug2Status.NotTakingPart, "") },
        { "5690", new LocalAuthorityDetails("Lewisham", Hug2Status.NotTakingPart, "") },
        { "3415", new LocalAuthorityDetails("Lichfield", Hug2Status.NotTakingPart, "") },
        { "2515", new LocalAuthorityDetails("Lincoln", Hug2Status.NotTakingPart, "") },
        { "4310", new LocalAuthorityDetails("Liverpool", Hug2Status.NotTakingPart, "") },
        { "5180", new LocalAuthorityDetails("London Borough of Bromley", Hug2Status.NotTakingPart, "") },
        { "5420", new LocalAuthorityDetails("London Borough of Haringey", Hug2Status.NotTakingPart, "") },
        { "5540", new LocalAuthorityDetails("London Borough of Hounslow", Hug2Status.NotTakingPart, "") },
        { "230", new LocalAuthorityDetails("Luton", Hug2Status.NotTakingPart, "") },
        { "2235", new LocalAuthorityDetails("Maidstone", Hug2Status.NotTakingPart, "") },
        { "1545", new LocalAuthorityDetails("Maldon", Hug2Status.NotTakingPart, "") },
        { "1820", new LocalAuthorityDetails("Malvern Hills", Hug2Status.NotTakingPart, "") },
        { "4215", new LocalAuthorityDetails("Manchester", Hug2Status.NotTakingPart, "") },
        { "3025", new LocalAuthorityDetails("Mansfield", Hug2Status.NotTakingPart, "") },
        { "2280", new LocalAuthorityDetails("Medway", Hug2Status.NotTakingPart, "") },
        { "2430", new LocalAuthorityDetails("Melton", Hug2Status.NotTakingPart, "") },
        { "3305", new LocalAuthorityDetails("Mendip", Hug2Status.NotTakingPart, "") },
        { "6925", new LocalAuthorityDetails("Merthyr Tydfil Ua", Hug2Status.NotTakingPart, "") },
        { "5720", new LocalAuthorityDetails("Merton", Hug2Status.NotTakingPart, "") },
        { "1135", new LocalAuthorityDetails("Mid Devon", Hug2Status.NotTakingPart, "") },
        { "3520", new LocalAuthorityDetails("Mid Suffolk", Hug2Status.NotTakingPart, "") },
        { "3830", new LocalAuthorityDetails("Mid Sussex", Hug2Status.NotTakingPart, "") },
        { "734", new LocalAuthorityDetails("Middlesbrough", Hug2Status.NotTakingPart, "") },
        { "9070", new LocalAuthorityDetails("Midlothian", Hug2Status.NotTakingPart, "") },
        { "435", new LocalAuthorityDetails("Milton Keynes", Hug2Status.NotTakingPart, "") },
        { "3620", new LocalAuthorityDetails("Mole Valley", Hug2Status.NotTakingPart, "") },
        { "6840", new LocalAuthorityDetails("Monmouthshire", Hug2Status.NotTakingPart, "") },
        { "9071", new LocalAuthorityDetails("Moray", Hug2Status.NotTakingPart, "") },
        { "6930", new LocalAuthorityDetails("Neath Port Talbot", Hug2Status.NotTakingPart, "") },
        { "1740", new LocalAuthorityDetails("New Forest", Hug2Status.NotTakingPart, "") },
        { "3030", new LocalAuthorityDetails("Newark and Sherwood", Hug2Status.NotTakingPart, "") },
        { "4510", new LocalAuthorityDetails("Newcastle Upon Tyne", Hug2Status.NotTakingPart, "") },
        { "3420", new LocalAuthorityDetails("Newcastle-Under-Lyme", Hug2Status.NotTakingPart, "") },
        { "5750", new LocalAuthorityDetails("Newham", Hug2Status.NotTakingPart, "") },
        { "6935", new LocalAuthorityDetails("Newport", Hug2Status.NotTakingPart, "") },
        { "9072", new LocalAuthorityDetails("North Ayrshire", Hug2Status.NotTakingPart, "") },
        { "1115", new LocalAuthorityDetails("North Devon", Hug2Status.NotTakingPart, "") },
        { "1035", new LocalAuthorityDetails("North East Derbyshire", Hug2Status.NotTakingPart, "") },
        { "2002", new LocalAuthorityDetails("North East Lincolnshire", Hug2Status.NotTakingPart, "") },
        { "1925", new LocalAuthorityDetails("North Hertfordshire", Hug2Status.NotTakingPart, "") },
        { "2520", new LocalAuthorityDetails("North Kesteven", Hug2Status.NotTakingPart, "") },
        { "9073", new LocalAuthorityDetails("North Lanarkshire", Hug2Status.NotTakingPart, "") },
        { "2003", new LocalAuthorityDetails("North Lincolnshire", Hug2Status.NotTakingPart, "") },
        { "2620", new LocalAuthorityDetails("North Norfolk", Hug2Status.NotTakingPart, "") },
        { "2840", new LocalAuthorityDetails("North Northamptonshire", Hug2Status.NotTakingPart, "") },
        { "121", new LocalAuthorityDetails("North Somerset", Hug2Status.NotTakingPart, "") },
        { "4515", new LocalAuthorityDetails("North Tyneside", Hug2Status.NotTakingPart, "") },
        { "3705", new LocalAuthorityDetails("North Warwickshire", Hug2Status.NotTakingPart, "") },
        { "2435", new LocalAuthorityDetails("North West Leicestershire", Hug2Status.NotTakingPart, "") },
        { "2745", new LocalAuthorityDetails("North Yorkshire", Hug2Status.NotTakingPart, "") },
        { "2935", new LocalAuthorityDetails("Northumberland", Hug2Status.NotTakingPart, "") },
        { "2625", new LocalAuthorityDetails("Norwich", Hug2Status.NotTakingPart, "") },
        { "3060", new LocalAuthorityDetails("Nottingham City", Hug2Status.NotTakingPart, "") },
        { "3710", new LocalAuthorityDetails("Nuneaton and Bedworth", Hug2Status.NotTakingPart, "") },
        { "2440", new LocalAuthorityDetails("Oadby and Wigston", Hug2Status.NotTakingPart, "") },
        { "4220", new LocalAuthorityDetails("Oldham", Hug2Status.NotTakingPart, "") },
        { "7655", new LocalAuthorityDetails("Ordnance Survey", Hug2Status.NotTakingPart, "") },
        { "9000", new LocalAuthorityDetails("Orkney Islands", Hug2Status.NotTakingPart, "") },
        { "3110", new LocalAuthorityDetails("Oxford", Hug2Status.NotTakingPart, "") },
        { "6845", new LocalAuthorityDetails("Pembrokeshire", Hug2Status.NotTakingPart, "") },
        { "2340", new LocalAuthorityDetails("Pendle", Hug2Status.NotTakingPart, "") },
        { "9074", new LocalAuthorityDetails("Perth and Kinross", Hug2Status.NotTakingPart, "") },
        { "540", new LocalAuthorityDetails("Peterborough", Hug2Status.NotTakingPart, "") },
        { "1160", new LocalAuthorityDetails("Plymouth", Hug2Status.NotTakingPart, "") },
        { "1775", new LocalAuthorityDetails("Portsmouth City Council", Hug2Status.NotTakingPart, "") },
        { "6850", new LocalAuthorityDetails("Powys", Hug2Status.NotTakingPart, "") },
        { "2345", new LocalAuthorityDetails("Preston", Hug2Status.NotTakingPart, "") },
        { "345", new LocalAuthorityDetails("Reading", Hug2Status.NotTakingPart, "") },
        { "5780", new LocalAuthorityDetails("Redbridge", Hug2Status.NotTakingPart, "") },
        { "728", new LocalAuthorityDetails("Redcar and Cleveland", Hug2Status.NotTakingPart, "") },
        { "1825", new LocalAuthorityDetails("Redditch", Hug2Status.NotTakingPart, "") },
        { "3625", new LocalAuthorityDetails("Reigate and Banstead", Hug2Status.NotTakingPart, "") },
        { "9075", new LocalAuthorityDetails("Renfrewshire", Hug2Status.NotTakingPart, "") },
        { "6940", new LocalAuthorityDetails("Rhondda Cynon Taff", Hug2Status.NotTakingPart, "") },
        { "2350", new LocalAuthorityDetails("Ribble Valley", Hug2Status.NotTakingPart, "") },
        { "5810", new LocalAuthorityDetails("Richmond Upon Thames", Hug2Status.NotTakingPart, "") },
        { "2720", new LocalAuthorityDetails("Richmondshire", Hug2Status.NotTakingPart, "") },
        { "4225", new LocalAuthorityDetails("Rochdale", Hug2Status.NotTakingPart, "") },
        { "1550", new LocalAuthorityDetails("Rochford", Hug2Status.NotTakingPart, "") },
        { "2355", new LocalAuthorityDetails("Rossendale", Hug2Status.NotTakingPart, "") },
        { "1430", new LocalAuthorityDetails("Rother", Hug2Status.NotTakingPart, "") },
        { "4415", new LocalAuthorityDetails("Rotherham", Hug2Status.NotTakingPart, "") },
        { "3715", new LocalAuthorityDetails("Rugby", Hug2Status.NotTakingPart, "") },
        { "3630", new LocalAuthorityDetails("Runnymede", Hug2Status.NotTakingPart, "") },
        { "3040", new LocalAuthorityDetails("Rushcliffe", Hug2Status.NotTakingPart, "") },
        { "1750", new LocalAuthorityDetails("Rushmoor", Hug2Status.NotTakingPart, "") },
        { "2470", new LocalAuthorityDetails("Rutland", Hug2Status.NotTakingPart, "") },
        { "2725", new LocalAuthorityDetails("Ryedale", Hug2Status.NotTakingPart, "") },
        { "4230", new LocalAuthorityDetails("Salford", Hug2Status.NotTakingPart, "") },
        { "4620", new LocalAuthorityDetails("Sandwell", Hug2Status.NotTakingPart, "") },
        { "2730", new LocalAuthorityDetails("Scarborough", Hug2Status.NotTakingPart, "") },
        { "9055", new LocalAuthorityDetails("Scottish Borders", Hug2Status.NotTakingPart, "") },
        { "3310", new LocalAuthorityDetails("Sedgemoor", Hug2Status.NotTakingPart, "") },
        { "4320", new LocalAuthorityDetails("Sefton Council", Hug2Status.NotTakingPart, "") },
        { "2735", new LocalAuthorityDetails("Selby", Hug2Status.NotTakingPart, "") },
        { "2245", new LocalAuthorityDetails("Sevenoaks", Hug2Status.NotTakingPart, "") },
        { "4420", new LocalAuthorityDetails("Sheffield", Hug2Status.NotTakingPart, "") },
        { "9010", new LocalAuthorityDetails("Shetland Islands", Hug2Status.NotTakingPart, "") },
        { "3245", new LocalAuthorityDetails("Shropshire", Hug2Status.NotTakingPart, "") },
        { "350", new LocalAuthorityDetails("Slough", Hug2Status.NotTakingPart, "") },
        { "4625", new LocalAuthorityDetails("Solihull", Hug2Status.NotTakingPart, "") },
        { "3300", new LocalAuthorityDetails("Somerset", Hug2Status.NotTakingPart, "") },
        { "3330", new LocalAuthorityDetails("Somerset West and Taunton ", Hug2Status.NotTakingPart, "") },
        { "9076", new LocalAuthorityDetails("South Ayrshire", Hug2Status.NotTakingPart, "") },
        { "530", new LocalAuthorityDetails("South Cambridgeshire", Hug2Status.NotTakingPart, "") },
        { "1040", new LocalAuthorityDetails("South Derbyshire", Hug2Status.NotTakingPart, "") },
        { "119", new LocalAuthorityDetails("South Gloucestershire", Hug2Status.NotTakingPart, "") },
        { "1125", new LocalAuthorityDetails("South Hams", Hug2Status.NotTakingPart, "") },
        { "2525", new LocalAuthorityDetails("South Holland", Hug2Status.NotTakingPart, "") },
        { "2530", new LocalAuthorityDetails("South Kesteven", Hug2Status.NotTakingPart, "") },
        { "930", new LocalAuthorityDetails("South Lakeland", Hug2Status.NotTakingPart, "") },
        { "9077", new LocalAuthorityDetails("South Lanarkshire", Hug2Status.NotTakingPart, "") },
        { "2630", new LocalAuthorityDetails("South Norfolk", Hug2Status.NotTakingPart, "") },
        { "3115", new LocalAuthorityDetails("South Oxfordshire", Hug2Status.NotTakingPart, "") },
        { "2360", new LocalAuthorityDetails("South Ribble", Hug2Status.NotTakingPart, "") },
        { "3325", new LocalAuthorityDetails("South Somerset", Hug2Status.NotTakingPart, "") },
        { "3430", new LocalAuthorityDetails("South Staffordshire", Hug2Status.NotTakingPart, "") },
        { "4520", new LocalAuthorityDetails("South Tyneside", Hug2Status.NotTakingPart, "") },
        { "1780", new LocalAuthorityDetails("Southampton", Hug2Status.NotTakingPart, "") },
        { "1590", new LocalAuthorityDetails("Southend-On-Sea", Hug2Status.NotTakingPart, "") },
        { "5840", new LocalAuthorityDetails("Southwark", Hug2Status.NotTakingPart, "") },
        { "3635", new LocalAuthorityDetails("Spelthorne", Hug2Status.NotTakingPart, "") },
        { "1930", new LocalAuthorityDetails("St Albans", Hug2Status.NotTakingPart, "") },
        { "4315", new LocalAuthorityDetails("St Helens Council", Hug2Status.NotTakingPart, "") },
        { "3425", new LocalAuthorityDetails("Stafford", Hug2Status.NotTakingPart, "") },
        { "3435", new LocalAuthorityDetails("Staffordshire Moorlands", Hug2Status.NotTakingPart, "") },
        { "1935", new LocalAuthorityDetails("Stevenage", Hug2Status.NotTakingPart, "") },
        { "9078", new LocalAuthorityDetails("Stirling", Hug2Status.NotTakingPart, "") },
        { "4235", new LocalAuthorityDetails("Stockport", Hug2Status.NotTakingPart, "") },
        { "738", new LocalAuthorityDetails("Stockton-On-Tees", Hug2Status.NotTakingPart, "") },
        { "3720", new LocalAuthorityDetails("Stratford-On-Avon", Hug2Status.NotTakingPart, "") },
        { "1625", new LocalAuthorityDetails("Stroud", Hug2Status.NotTakingPart, "") },
        { "4525", new LocalAuthorityDetails("Sunderland", Hug2Status.NotTakingPart, "") },
        { "3640", new LocalAuthorityDetails("Surrey Heath", Hug2Status.NotTakingPart, "") },
        { "5870", new LocalAuthorityDetails("Sutton", Hug2Status.NotTakingPart, "") },
        { "2255", new LocalAuthorityDetails("Swale", Hug2Status.NotTakingPart, "") },
        { "6855", new LocalAuthorityDetails("Swansea", Hug2Status.NotTakingPart, "") },
        { "3935", new LocalAuthorityDetails("Swindon", Hug2Status.NotTakingPart, "") },
        { "4240", new LocalAuthorityDetails("Tameside", Hug2Status.NotTakingPart, "") },
        { "3445", new LocalAuthorityDetails("Tamworth", Hug2Status.NotTakingPart, "") },
        { "3645", new LocalAuthorityDetails("Tandridge", Hug2Status.NotTakingPart, "") },
        { "1130", new LocalAuthorityDetails("Teignbridge", Hug2Status.NotTakingPart, "") },
        { "3240", new LocalAuthorityDetails("Telford and Wrekin", Hug2Status.NotTakingPart, "") },
        { "1560", new LocalAuthorityDetails("Tendring", Hug2Status.NotTakingPart, "") },
        { "1760", new LocalAuthorityDetails("Test Valley", Hug2Status.NotTakingPart, "") },
        { "1630", new LocalAuthorityDetails("Tewkesbury", Hug2Status.NotTakingPart, "") },
        { "2260", new LocalAuthorityDetails("Thanet District", Hug2Status.NotTakingPart, "") },
        { "1940", new LocalAuthorityDetails("Three Rivers", Hug2Status.NotTakingPart, "") },
        { "1595", new LocalAuthorityDetails("Thurrock", Hug2Status.NotTakingPart, "") },
        { "2265", new LocalAuthorityDetails("Tonbridge and Malling", Hug2Status.NotTakingPart, "") },
        { "1165", new LocalAuthorityDetails("Torbay", Hug2Status.NotTakingPart, "") },
        { "6945", new LocalAuthorityDetails("Torfaen", Hug2Status.NotTakingPart, "") },
        { "1145", new LocalAuthorityDetails("Torridge", Hug2Status.NotTakingPart, "") },
        { "5900", new LocalAuthorityDetails("Tower Hamlets", Hug2Status.NotTakingPart, "") },
        { "4245", new LocalAuthorityDetails("Trafford", Hug2Status.NotTakingPart, "") },
        { "2270", new LocalAuthorityDetails("Tunbridge Wells", Hug2Status.NotTakingPart, "") },
        { "1570", new LocalAuthorityDetails("Uttlesford", Hug2Status.NotTakingPart, "") },
        { "6950", new LocalAuthorityDetails("Vale of Glamorgan", Hug2Status.NotTakingPart, "") },
        { "3120", new LocalAuthorityDetails("Vale of White Horse", Hug2Status.NotTakingPart, "") },
        { "4725", new LocalAuthorityDetails("Wakefield", Hug2Status.NotTakingPart, "") },
        { "4630", new LocalAuthorityDetails("Walsall", Hug2Status.NotTakingPart, "") },
        { "5930", new LocalAuthorityDetails("Waltham Forest", Hug2Status.NotTakingPart, "") },
        { "5960", new LocalAuthorityDetails("Wandsworth", Hug2Status.NotTakingPart, "") },
        { "655", new LocalAuthorityDetails("Warrington", Hug2Status.NotTakingPart, "") },
        { "3725", new LocalAuthorityDetails("Warwick", Hug2Status.NotTakingPart, "") },
        { "1945", new LocalAuthorityDetails("Watford", Hug2Status.NotTakingPart, "") },
        { "3650", new LocalAuthorityDetails("Waverley", Hug2Status.NotTakingPart, "") },
        { "1435", new LocalAuthorityDetails("Wealden", Hug2Status.NotTakingPart, "") },
        { "1950", new LocalAuthorityDetails("Welwyn Hatfield", Hug2Status.NotTakingPart, "") },
        { "340", new LocalAuthorityDetails("West Berkshire", Hug2Status.NotTakingPart, "") },
        { "1150", new LocalAuthorityDetails("West Devon", Hug2Status.NotTakingPart, "") },
        { "9057", new LocalAuthorityDetails("West Dunbartonshire", Hug2Status.NotTakingPart, "") },
        { "2365", new LocalAuthorityDetails("West Lancashire", Hug2Status.NotTakingPart, "") },
        { "2535", new LocalAuthorityDetails("West Lindsey", Hug2Status.NotTakingPart, "") },
        { "9079", new LocalAuthorityDetails("West Lothian", Hug2Status.NotTakingPart, "") },
        { "2845", new LocalAuthorityDetails("West Northamptonshire", Hug2Status.NotTakingPart, "") },
        { "3125", new LocalAuthorityDetails("West Oxfordshire", Hug2Status.NotTakingPart, "") },
        { "3545", new LocalAuthorityDetails("West Suffolk", Hug2Status.NotTakingPart, "") },
        { "9020", new LocalAuthorityDetails("Western Isles", Hug2Status.NotTakingPart, "") },
        { "935", new LocalAuthorityDetails("Westmorland and Furness", Hug2Status.NotTakingPart, "") },
        { "4250", new LocalAuthorityDetails("Wigan", Hug2Status.NotTakingPart, "") },
        { "3940", new LocalAuthorityDetails("Wiltshire", Hug2Status.NotTakingPart, "") },
        { "1765", new LocalAuthorityDetails("Winchester", Hug2Status.NotTakingPart, "") },
        { "355", new LocalAuthorityDetails("Windsor and Maidenhead", Hug2Status.NotTakingPart, "") },
        { "4325", new LocalAuthorityDetails("Wirral", Hug2Status.NotTakingPart, "") },
        { "3655", new LocalAuthorityDetails("Woking", Hug2Status.NotTakingPart, "") },
        { "360", new LocalAuthorityDetails("Wokingham", Hug2Status.NotTakingPart, "") },
        { "4635", new LocalAuthorityDetails("Wolverhampton", Hug2Status.NotTakingPart, "") },
        { "1835", new LocalAuthorityDetails("Worcester", Hug2Status.NotTakingPart, "") },
        { "3835", new LocalAuthorityDetails("Worthing", Hug2Status.NotTakingPart, "") },
        { "6955", new LocalAuthorityDetails("Wrexham", Hug2Status.NotTakingPart, "") },
        { "1840", new LocalAuthorityDetails("Wychavon", Hug2Status.NotTakingPart, "") },
        { "2370", new LocalAuthorityDetails("Wyre", Hug2Status.NotTakingPart, "") },
        { "1845", new LocalAuthorityDetails("Wyre Forest", Hug2Status.NotTakingPart, "") },
        { "2741", new LocalAuthorityDetails("York", Hug2Status.NotTakingPart, "") },
    };
}

